filebeat.inputs:
  - type: filestream
    id: docker-logs
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~

processors:
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"

logging.to_files: false
logging.level: info